### ISSUE TITLE
Error: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

### ISSUE THREAD

**Issue by mukundkatpatal** [yannbf/the-packages#10]
I recently moved from storybook 6 to 7 for angular 14. My mdx was old format.
I am getting below error when I try `npx @hipster/mdx2-issue-checker examples/styles` on a windows machine.
`
examples\styles\utilities.stories.mdx
  1:1  error  Error: Could not find module `C:\Users\vv002e\AppData\Local\npm-cache\_npx\2f3fd0965f9e4209\node_modules\remark-mdx\index.js`
Error: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/import-meta-resolve/lib/errors.js:292:5)
    at throwIfUnsupportedURLScheme (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/import-meta-resolve/lib/resolve.js:1155:11)
    at defaultResolve (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/import-meta-resolve/lib/resolve.js:1215:3)
    at resolve (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/import-meta-resolve/index.js:30:12)
    at attempt (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/load-plugin/index.js:167:15)
    at resolvePlugin (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/load-plugin/index.js:148:16)
    at async addModule (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/unified-engine/lib/configuration.js:325:12)
    at async use (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/unified-engine/lib/configuration.js:308:7)
    at async addIn (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/unified-engine/lib/configuration.js:297:9)
    at async addPreset (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/unified-engine/lib/configuration.js:258:7)
    at FormattedError (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/fault/index.js:39:12)
    at Function.<anonymous> (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/unified-engine/lib/configuration.js:332:15)
    at Function.freeze (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/unified/lib/index.js:136:36)
    at Function.parse (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/unified/lib/index.js:262:15)
    at parse (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/unified-engine/lib/file-pipeline/parse.js:50:36)
    at wrapped (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/trough/index.js:115:27)
    at next (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/trough/index.js:65:23)
    at done (file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/trough/index.js:148:7)
    at file:///C:/Users/vv002e/AppData/Local/npm-cache/_npx/2f3fd0965f9e4209/node_modules/unified-engine/lib/file-pipeline/read.js:42:7
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)`

**Comment by yannbf** [comment]
Hey there! Thanks for reporting the issue.
I unfortunately do not have time to dive deep into this, neither do I have a Windows machine to test it on.

Try the following command instead:
```
npx -p remark-cli -p remark-mdx . --use remark-mdx --ext .mdx
```

if that does not work, you probably have to globally (or locally, temporarily) install `remark-mdx`, then run 

```
npx -p remark-cli . --use remark-mdx --ext .mdx
```

I'd highly recommend you to use the [VSCode MDX extension](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx) which parses your MDX files and will tell you about issues, in a better way even.
